config/routes.rb
Rails.application.routes.draw do

  # ユーザー用
  # URL /customers/sign_in ...（URLが自動で変更してくれる）
  # Webページに表示されるものを制限かける
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # devise生成したコントローラーに手動でアクションを追加した時は、devise_scopeの中に追記
  devise_scope :user do
    # ゲストサインイン
    post "user/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

  # ユーザー側
  scope module: :user do
    root "homes#top"
    # マイページ
    get 'users/mypage/:id' => 'users#show', as: :users_mypage
    # 退会確認ページ
    get 'users/confirm_withdraw' => 'users#confirm_withdraw', as: :users_confirm_withdraw
    # 退会機能
    patch 'users/withdraw' => 'users#withdraw'
    end

  # admin側
  namespace :admin do
    get "/" => "homes#top"
    resources :users, only: [:index]
    # 寺社
    resources :places, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  end

end

app/models/place.rb
# 寺社モデル
class Place < ApplicationRecord

  #バリデーション設定
  # カテゴリーラジオボタンバリデーション
  validates :category, presence: true
  # 寺社名バリデーション
  validates :name, presence: true, length: { maximum: 30 }
  # 郵便番号ハイフンなしバリデーション（７桁：半角数字のみ）
  validates :postcode, format: { with: /\A[0-9]{7}\z/ }
  # 住所バリデーション
  validates :address, presence: true, length: { maximum: 80 }
  # 電話番号：空でも許可して、フォームに入力された場合は半角数字のみ許可するバリデーション
  validates :phone_number, allow_blank: true, format: { with: /\A[0-9]+\z/ }
  # 拝観料のバリデーション
  # 0〜9,999,999までの数字範囲指定
  validates :fee, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 9_999_999 },
                  # フォームに入力する数字は半角数字のみ
                  format: { with: /\A[0-9]+\z/ }
  validates :sect, length: { maximum: 30 }
  # ペット状況ラジオボタンバリデーション
  validates :pet, presence: true
  # 画像枚数のバリデーション
  validates :images, limit: { min: 0, max: 3 }

  #アソシエーション
  # 都道府県とのアソシエーション（寺社モデルがNの１：N）
  belongs_to :prefecture

  #enum設定
  # 寺社（shrine: 神社　temple: お寺）
  enum category: { shrine: 0, temple: 1 }
  # ペット入場（ok: OK, ng: NG, not_clea: 不明）
  enum pet: { not_clea: 0, ok: 1, ng: 2 }

  # imageカラム
  # has_one_attached :image 単数投稿
  # 複数投稿
  has_many_attached :images

  # 画像が存在するかどうか判断するメソッド
  def get_place_image
    # 存在しなかった場合no_image.pngを使用
    # []配列にすることでeachが使用できるように設定
    (images.attached?) ? images : ['place_no_image.png']
  end

end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < ApplicationController

  # アクセス制限
  before_action :authenticate_admin!

  def new
    @place = Place.new
  end

  def create
    # 許可されたデータが変数に格納
    @place = Place.new(place_params)
    # 保存が成功した場合
    if @place.save
      # フラッシュメッセージを表示して寺社詳細ページへ遷移
      redirect_to admin_place_path(@place), info: "投稿されました"
    # それ以外の場合（失敗した場合）
    else
      # 寺社新規投稿ページへ遷移
      render :new
    end
  end

  def index
    @places = Place.all
  end

  def show
    # 特定の寺社データ格納
    @place = Place.find(params[:id])
  end

  def edit
    # 特定の寺社のデータを格納
    @place = Place.find(params[:id])
  end

  # 更新機能
  def update
    # 特定の寺社データを格納
    @place = Place.find(params[:id])
    # 更新に成功したら
    if @place.update(place_params)
      # 更新された寺社詳細ページへ遷移
      redirect_to admin_place_path(@place), info: "編集されました"
    else
      # 失敗した寺社編集ページへ遷移
      render :edit
    end
  end

  def destroy
  end

  private

  def place_params
    params.require(:place).permit(
    :prefecture_id,
    :user_id,
    :admin_id,
    :category,
    :name,
    :address,
    :postcode,
    :phone_number,
    :got,
    :sect,
    :pet,
    :fee,
    :start_time,
    :end_time,
    images: []
    # 前の結果に対して、付け加える
    ).merge(
        # ユーザーIDが存在するかどうか判断。存在しなかった場合nil
        user_id: user_signed_in? ? current_user.id : nil,
        # アドミンIDが存在するかどうか判断。存在しなかった場合nil
        admin_id: admin_signed_in? ? current_admin.id : nil
      )
  end

end

app/helpers/admin/places_helper.rb
module Admin::PlacesHelper
end

app/views/admin/places/edit.html.erb
<!-- 管理者側寺社投稿ページのコンテナ -->
<div class="container">
  <!--行を示す要素で、内部のコンテンツを行内に配置-->
  <div class="row">
    <!-- 左側のコラム -->
    <div class="col-md-8">
      <!-- 寺社フォーム部分テンプレートを描画 -->
      <%= render 'layouts/place_form',
        place: @place,
        submit: "編集",
        target_path: admin_place_path(@place) %>
    </div>
  </div>
</div>

app/views/admin/places/index.html.erb
<!-- 管理者側寺社投稿ページのコンテナ -->
<div class="container">
  <!--行を示す要素で、内部のコンテンツを行内に配置-->
  <div class="row">
    <!-- 左側のコラム (幅: 5カラム) -->
    <div class="col-md-12">
      <h2 class="text-center">admin/place/index</h2>
      <!--寺社一覧を繰り返し表示-->
      <% @places.each do |place| %>
        <div class="card mb-5">
          <div class="card-header">
            <h5 class="card-text text-center">
              <%= link_to admin_place_path(place) do %>
                <%= place.name %>
              <% end %>
            </h5>

            <!--地方名/都道府県名表示-->
            <div class="card-text">
              <!--地方名を押すとその地方だけの一覧を表示-->
              <%= place.prefecture.area.name %>/
              <!--都道府県を押すとその都道府県だけの一覧を表示-->
              <%= place.prefecture.name %>
            </div>

            <!--郵便番号＆住所表示-->
            <div class="card-text">
              <div class="row">
                <!--郵便番号-->
                <div class="col-md-3">
                  〒<%= place.postcode.insert(3, "-") %>
                </div>
                <!--都道府県名＋住所-->
                <div class="col-md-9 text-right">
                  <%= place.prefecture.name %><%= place.address %>
                </div>
              </div>
            </div>
          </div>

          <div class="card-body">
            画像表示
          </div>

          <div class="card-footer text-right text-muted">
            <div>投稿日：<%= place.created_at.strftime("%Y年%m月%d日") %></div>
            <div>更新日：<%= place.updated_at.strftime("%Y年%m月%d日") %></div>
          </div>

        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/places/new.html.erb
<!-- 管理者側寺社投稿ページのコンテナ -->
<div class="container">
  <!--行を示す要素で、内部のコンテンツを行内に配置-->
  <div class="row">
    <!-- 左側のコラム -->
    <div class="col-md-8">
      <!-- 寺社フォーム部分テンプレートを描画 -->
      <%= render 'layouts/place_form',
        place: @place,
        submit: "投稿",
        target_path: admin_places_path %>
    </div>
  </div>
</div>

app/views/admin/places/show.html.erb
<!-- 管理者側寺寺社詳細ページのコンテナ-->
<div class="container o-8column">
  <!--行を示す要素で、内部のコンテンツを行内に配置-->
  <div class="row">
    <div class="col-md-12">

      <h2><%= @place.name %></h2>

      <div class="text-center">
        <!--画像を繰り返し表示-->
        <% @place.get_place_image.each do |img| %>
        <!--alt: 画像が表示されなかった場合表示される文字-->
         <%= image_tag img, alt: 'Place Image', class: 'img-fluid w-100' %>
        <% end %>
      </div>

      <ul>
        <!--insert：文字列の特定した位置に指定した文字や文字列を挿入するメソッド-->
        <li><strong>郵便番号：〒</strong><%= @place.postcode.insert(3, "-") %></li>
        <li><strong>住所：</strong><%= @place.prefecture.name %><%= @place.address %></li>
        <!--unless：条件分岐がelseしかない場合に使用。blank?：データが存在するかどうか判断-->
        <% unless @place.phone_number.blank? %>
          <!--存在した場合：電話番号-->
          <li><strong>電話番号：☎</strong>︎ <%= @place.phone_number.insert(4, '-').insert(9, '-') %></li>
        <% end %>
        <!--データが空でない場合-->
        <% unless @place.start_time.blank? && @place.end_time.blank? %>
        <!--営業時間：開始時間〜終了時間-->
          <li><strong>営業時間：</strong> <%= @place.start_time.strftime('%H:%M') %>〜<%= @place.end_time.strftime('%H:%M') %></li>
        <% end %>
        <!--拝観料-->
        <li><strong>拝観料：¥</strong> <%= @place.fee %></li>
        <!--ペット状況-->
        <li><strong>ぺっと状況：</strong> <%= @place.pet_i18n %></li>
      </ul>

      <%= link_to "編集", edit_admin_place_path(@place), class: "btn btn-sm btn-info w-25 mt-1 c-btn" %>

    </div>
  </div>
</div>