config/routes.rb
Rails.application.routes.draw do

  # ユーザー用
  # URL /customers/sign_in ...（URLが自動で変更してくれる）
  # Webページに表示されるものを制限かける
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # devise生成したコントローラーに手動でアクションを追加した時は、devise_scopeの中に追記
  devise_scope :user do
    # ゲストサインイン
    post "user/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

  # ユーザー側
  scope module: :user do
    root "homes#top"
    # マイページ
    get 'users/mypage/:id' => 'users#show', as: :users_mypage
    # 退会確認ページ
    get 'users/confirm_withdraw' => 'users#confirm_withdraw', as: :users_confirm_withdraw
    # 退会機能
    patch 'users/withdraw' => 'users#withdraw'
    end

  # admin側
  namespace :admin do
    get "/" => "homes#top"
    resources :users, only: [:index]
    # 寺社
    resources :places, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController

  def top
    @user = current_user
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/views/admin/homes/top.erb
<!--admin側Topページ-->

<h1 class="text-center">admin/Top</h1>

  ログイン中
  <!--btn-block＝幅いっぱいに広がる-->
  <%= link_to 'サインアウト', destroy_admin_session_path, class: "btn btn-secondary btn-block", method: :delete %>
  <%= link_to '会員一覧', admin_users_path, class: "btn btn-secondary btn-block" %>
  <%= link_to '寺社投稿', new_admin_place_path, class: "btn btn-secondary btn-block" %>
  <%= link_to '寺社一覧', admin_places_path, class: "btn btn-secondary btn-block" %>