config/routes.rb
Rails.application.routes.draw do

  # ユーザー用
  # URL /customers/sign_in ...（URLが自動で変更してくれる）
  # Webページに表示されるものを制限かける
  devise_for :users,skip: [:passwords], controllers: {
    registrations: "user/registrations",
    sessions: 'user/sessions'
  }

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
    sessions: "admin/sessions"
  }

  # devise生成したコントローラーに手動でアクションを追加した時は、devise_scopeの中に追記
  devise_scope :user do
    # ゲストサインイン
    post "user/guest_sign_in", to: "user/sessions#guest_sign_in"
  end

  # ユーザー側
  scope module: :user do
    root "homes#top"
    # マイページ
    get 'users/mypage/:id' => 'users#show', as: :users_mypage
    # 退会確認ページ
    get 'users/confirm_withdraw' => 'users#confirm_withdraw', as: :users_confirm_withdraw
    # 退会機能
    patch 'users/withdraw' => 'users#withdraw'
    end

  # admin側
  namespace :admin do
    get "/" => "homes#top"
    resources :users, only: [:index]
    # 寺社
    resources :places, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/area.rb
# 地方モデル
class Area < ApplicationRecord

  #バリデーション設定
  validates :name, presence: true

  #アソシエーション
  #都道府県に対して地方が１：N
  has_many :prefectures, dependent: :destroy

end

app/models/place.rb
# 寺社モデル
class Place < ApplicationRecord

  #バリデーション設定
  # カテゴリーラジオボタンバリデーション
  validates :category, presence: true
  # 寺社名バリデーション
  validates :name, presence: true, length: { maximum: 30 }
  # 郵便番号ハイフンなしバリデーション（７桁：半角数字のみ）
  validates :postcode, format: { with: /\A[0-9]{7}\z/ }
  # 住所バリデーション
  validates :address, presence: true, length: { maximum: 80 }
  # 電話番号：空でも許可して、フォームに入力された場合は半角数字のみ許可するバリデーション
  validates :phone_number, allow_blank: true, format: { with: /\A[0-9]+\z/ }
  # 拝観料のバリデーション
  # 0〜9,999,999までの数字範囲指定
  validates :fee, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 9_999_999 },
                  # フォームに入力する数字は半角数字のみ
                  format: { with: /\A[0-9]+\z/ }
  validates :sect, length: { maximum: 30 }
  # ペット状況ラジオボタンバリデーション
  validates :pet, presence: true
  # 画像枚数のバリデーション
  validates :images, limit: { min: 0, max: 3 }

  #アソシエーション
  # 都道府県とのアソシエーション（寺社モデルがNの１：N）
  belongs_to :prefecture

  #enum設定
  # 寺社（shrine: 神社　temple: お寺）
  enum category: { shrine: 0, temple: 1 }
  # ペット入場（ok: OK, ng: NG, not_clea: 不明）
  enum pet: { not_clea: 0, ok: 1, ng: 2 }

  # imageカラム
  # has_one_attached :image 単数投稿
  # 複数投稿
  has_many_attached :images

  # 画像が存在するかどうか判断するメソッド
  def get_place_image
    # 存在しなかった場合no_image.pngを使用
    # []配列にすることでeachが使用できるように設定
    (images.attached?) ? images : ['place_no_image.png']
  end

end

app/models/prefecture.rb
# 都道府県モデル
class Prefecture < ApplicationRecord

  #バリデーション設定
  validates :name, presence: true

  #アソシエーション
  # 地方に対してのアソシエーション（都道府県がNの１：N）
  belongs_to :area
  # 寺社に対するアソシエーション（都道府県が１の１：N)
  has_many :places, dependent: :destroy

end

app/models/user.rb
# ユーザーモデル
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #バリデーション設定
  # ユーザーネームは30文字で同名はNG(レイアウトの問題ならばCSSで適用した方がいい)
  validates :name, presence: true, length: { maximum: 30 }

  #画像カラム
  has_one_attached :image

  # 定数にメールアドレスを格納
  GUEST_USER_EMAIL = "guest@example.com"

  # self:インスタンスを作成しなくてもメソッドが呼び出せる（クラスメソッドという）
  # IDを必要としない場合にselfを使用するみたいな雰囲気
  def self.guest
    # メールアドレスが存在するか判断（存在しない場合はcreate）
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      # assign_attributesで足りない情報を補完する(null: falseの設定があるカラム)
      user.assign_attributes(
        password: SecureRandom.urlsafe_base64,
        name: "guestuser"
      )
    end
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
end

app/controllers/admin/places_controller.rb
class Admin::PlacesController < ApplicationController

  # アクセス制限
  before_action :authenticate_admin!

  def new
    @place = Place.new
  end

  def create
    # 許可されたデータが変数に格納
    @place = Place.new(place_params)
    # 保存が成功した場合
    if @place.save
      # フラッシュメッセージを表示して寺社詳細ページへ遷移
      redirect_to admin_place_path(@place), info: "投稿されました"
    # それ以外の場合（失敗した場合）
    else
      # 寺社新規投稿ページへ遷移
      render :new
    end
  end

  def index
    @places = Place.all
  end

  def show
    # 特定の寺社データ格納
    @place = Place.find(params[:id])
  end

  def edit
    # 特定の寺社のデータを格納
    @place = Place.find(params[:id])
  end

  # 更新機能
  def update
    # 特定の寺社データを格納
    @place = Place.find(params[:id])
    # 更新に成功したら
    if @place.update(place_params)
      # 更新された寺社詳細ページへ遷移
      redirect_to admin_place_path(@place), info: "編集されました"
    else
      # 失敗した寺社編集ページへ遷移
      render :edit
    end
  end

  def destroy
  end

  private

  def place_params
    params.require(:place).permit(
    :prefecture_id,
    :user_id,
    :admin_id,
    :category,
    :name,
    :address,
    :postcode,
    :phone_number,
    :got,
    :sect,
    :pet,
    :fee,
    :start_time,
    :end_time,
    images: []
    # 前の結果に対して、付け加える
    ).merge(
        # ユーザーIDが存在するかどうか判断。存在しなかった場合nil
        user_id: user_signed_in? ? current_user.id : nil,
        # アドミンIDが存在するかどうか判断。存在しなかった場合nil
        admin_id: admin_signed_in? ? current_admin.id : nil
      )
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController

  def index
    @users = User.all
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # アクセス制限
  before_action :configure_permitted_parameters, if: :devise_controller?

  # フラッシュメッセージのbootstrap
  add_flash_types :secondary, :success, :danger, :warning, :info, :light, :dark

  protected

  # サインアップ時にnameも許可
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

# deviseログインを手動で別ページに遷移させるメソッド
# def after_sign_in_path_for(resource)
#   your_desired_path # 例: dashboard_path
# end

app/controllers/user/homes_controller.rb
class User::HomesController < ApplicationController

  def top
    @user = current_user
  end

end

app/controllers/user/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/user/users_controller.rb
class User::UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  # 退会確認
  def confirm_withdraw
    # ログインしているユーザー本人のデータ
    @user = current_user
  end

  # 退会
  def withdraw
    # ログインしているユーザー本人のデータ
    @user = current_user
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    # "#{}で文字列の中に変数を入れられる"
    @user.update(is_deleted: true, name: "退会済み")
    # byebug
    # 退会した時点でログアウトする
    reset_session
    # 成功メッセージ
    redirect_to root_path, info: "ご利用ありがとうございました"
  end

end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/places_helper.rb
module Admin::PlacesHelper
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user/homes_helper.rb
module User::HomesHelper
end

app/helpers/user/users_helper.rb
module User::UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<!--ここ何-->
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_flash_messages.html.erb
<!--フラッシュメッセージの部分テンプレート-->
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %> text-center js-flash"><%= message %></div>
<% end %>

app/views/layouts/_place_form.html.erb
<!--寺社投稿・編集部分テンプレート-->
<!--JavaScript反映-->
<%= javascript_pack_tag 'place_form' %>

<!--都道府県のレコードよりさきに地方のレコードを取り出している：includes-->
<% prefectures = Prefecture.includes(:area) %>

<!--地方IDデータが存在していた場合、都道府県セレクトボックスの中身を対応したものにして、存在しなかった場合は空で返す-->
<!--ここで新規フォームと編集フォームのIf文（ place.prefecture_id ?）追加したことによって両方のページで共通フォームを使用可能になっている-->
<% target_prefectures = place.prefecture_id ? prefectures.where('areas.id': place.prefecture.area_id).map{|o| [o.name, o.id] } : [] %>

<%= form_with model: place, url: target_path do |f| %>

<!--バリデーション呼び出し-->
<%= render "layouts/validates", model: f.object %>

<!--HTMLのpreタグ。このタグで囲んであげることでデータが見やすくなる-->
<!--<pre>-->
  <!--データがどのような形で入っているか確認できる-->
  <%#= Area.all.map{|a| [a.id, a.name]}.inspect %>
<!--</pre>-->

<h2 class="text-center mb-5"><%= "寺社#{submit}" %></h2>

<!--画像フォーム-->
<div class="row">
  <div class="col-12 w-100">
  <!--画像が存在するかどうか判断-->
  <% if place.images.attached? %>
    <%  place.images.each do |image| %>
      <%= image_tag image, alt: 'Place Image', class: 'img-fluid w-100' %>
    <% end %>
  <% else %><!--存在しなかった場合-->
    <%= image_tag "place_no_image.png", style: "width: 50;", id: 'imagePreview', class: "img-fluid mb-3" %>
  <% end %>
  </div>
</div>
<!--画像複数投稿フォーム（multiple: true：複数投稿を可能にしている）-->
<%= f.file_field :images, multiple: true, id: "imageField" %>
<!--単数画像投稿の場合のコード-->
<%#= f.file_field :image, id: "imageField" %>

<!--寺社選択ラジオボタン-->
<div class="form-group mt-5">
  <!--左辺がbに入る。この場合はfirst。enumのverとkeyのような考え方-->
  <%= f.collection_radio_buttons :category, Place.categories_i18n, :first, :last do |b| %>
    <!--ラジオボタンを作成して、文字も表示させクリックに反応するようにしている-->
    <%= b.label(class: "mr-2") { b.radio_button(class: "mr-1") + b.text } %>
  <% end %>
</div>

<!--寺社名フォーム-->
<div class="form-group">
  <%= f.label :寺社名 %><font color="red">*必須</font>
  <!--placeholder: "寺社名"入力フォームのヒント-->
  <%= f.text_field :name, placeholder: "寺社名（必須）", class: "form-control" %>
</div>

<!--郵便番号フォーム-->
<div class="form-group">
  <%= f.label :郵便番号 %><font color="red">*必須</font>
  <%= f.text_field :postcode, placeholder: "ハイフンなし（必須）", class: "form-control" %>
</div>

<!--地方選択セレクトボックス-->
<div class="form-group">
  <%= f.label :地方 %><font color="red">*必須</font>
  <!--f.selectを使用するときは機能とHTML要素に{ }をつけてあげないとブートストラップが反映-->
  <!--map：値になるものと表示を設定してハッシュに渡す。-->
  <%#= f.select :area_id, Area.all.map{|a| [a.name, a.id]}, { prompt: "地方を選択してください" }, { class: "form-control" } %>
  <!--上記のコードとやっていることは一緒。フォームヘルパーメソッドの一つなのでこちらの方がよい-->
  <!--collection_select：モデルのデータを全て取得して、どれをkeyにしてvarにするか設定している-->
  <%= f.collection_select :area_id, Area.all, :id, :name,
    { include_blank: "地方を選択してください" },
    { class: "form-control", id: "area-select" } %>
  </div>

<!--都道府県選択セレクトボックス（地方選択によって中身が変わる）-->
<div class="form-group">
  <%= f.label :都道府県 %><font color="red">*必須</font>
  <%= f.collection_select :prefecture_id, target_prefectures, :last, :first,
    { include_blank: "都道府県を選択してください" },
    { class: "form-control", id: "prefecture-select",
       data: { json: (prefectures.map{|o| { id: o.id, name: o.name, area_id: o.area.id } }).to_json } } %>
</div>

<!--住所カラム（市区町村から）-->
<div class="form-group">
  <%= f.label :市区町村 %><font color="red">*必須</font>
  <%= f.text_field :address, placeholder: "市区町村から記入してください", class: "form-control" %>
</div>

<!--電話番号カラム-->
<div class="form-group">
  <%= f.label :電話番号 %>
  <%= f.text_field :phone_number, placeholder: "ハイフンなし", class: "form-control" %>
</div>

<!--営業時間フォーム-->
<div class="form-group">
  <div class="row">
    <div class="col-md-5">
      <%= f.label :start_time, '営業開始' %>
      <%= f.time_field :start_time, class: "form-control" %>
    </div>
    <div class="col-md-5">
      <%= f.label :end_time, '営業修了' %>
      <%= f.time_field :end_time, class: "form-control" %>
    </div>
  </div>
</div>

<!--拝観料フォーム-->
<div class="form-group">
  <%= f.label :fee, "拝観料" %>
  <%= f.text_field :fee, placeholder: "大人料金", class: "form-control" %>
</div>

<!--神様カラムあとでテーブル作成-->
<!--<div class="form-group">-->
  <%#= f.label :御祭神 %>
  <%#= f.text_field :got, placeholder: "主祭神を記入してください", class: "form-control" %>
<!--</div>-->

<!--宗派カラム-->
<div class="form-group">
  <%= f.label :宗派 %>
  <%= f.text_field :sect, placeholder: "宗派", class: "form-control" %>
</div>

<!--ペット選択セレクトボックス-->
<div class="form-group">
  <%= f.label :ペット %><font color="red">*必須</font>
  <!--_i18nで日本語化。
  invertでverとkeyを反転させている。
  見た目上では数値ではなく文字列として表示されているが見た目上の話なので日本化と混じった考え方をしないように注意-->
  <%= f.select :pet, Place.pets_i18n.invert, { prompt: "選択してください" }, { class: "form-control" } %>
</div>

<div>
  <%= f.submit submit, class: "btn btn-info btn-block mb-5" %>
</div>

<% end %>

app/views/layouts/_validates.html.erb
<!--バリデーションメッセージ表示-->
<% if model.errors.any? %>
<div class="alert alert-danger">
  <h5><strong><%= model.errors.count %>件のエラーが発生しました</strong></h5>
  <ul>
    <% model.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qiita</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--FontAwesomet読み込み-->
    <script src="https://kit.fontawesome.com/cb1a1fa502.js" crossorigin="anonymous"></script>
    <!--変更前-->
    <%#= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!--変更後-->
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!--フラッシュメッセージの部分テンプレート-->
    <%= render 'layouts/flash_messages' %>

    <%= yield %>
  </body>
</html>